#!/data/data/com.termux/files/usr/bin/sh

chmod 755 $PREFIX/bin/shizuku
chmod 755 $PREFIX/bin/shizuku-setup
chmod 755 $PREFIX/bin/shizuku-desetup
chmod 755 $PREFIX/bin/shizuku-help
chmod 755 $PREFIX/bin/shizuku-info

shizuku-setup

echo " "
echo 'Package termux-shizuku-tools 2.0 by AlexeiCrystal installed!' 
echo 'For a list of commands, run "shizuku-help"'
